name: Next.JS Ci

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Install bun
      uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      run: bun install
    - name: Build app
      run: bun run build