# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup env
      run: npm install express && npm install typescript && npm install tailwindcss && npm install postcss-cli && npm install nodemon && npm install --save-dev @types/express autoprefixer nodemon
    - run: npm ci
    - name: Build
      run: ls && tsc
    - run: npx postcss src/webpage/style.css -o build/webpage/output.css
    - run: npm run build --if-present
